### ISSUE TITLE
CI failure: Could not find module ‘Glean.Indexer.Swift’

### ISSUE THREAD

**Issue by simonmar** [facebookincubator/Glean#515]
Probably broken by 608725d

```
glean/index/list/Glean/Indexer/List.hs:37:1: error:
    Could not find module ‘Glean.Indexer.Swift’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
37 | import qualified Glean.Indexer.Swift as Swift
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
